version: '3.5'

services:
  proxy:
    container_name: reverse-proxy
    image: jwilder/nginx-proxy
    restart: always
    volumes:
     - certs:/etc/nginx/certs:ro
     - vhost.d:/etc/nginx/vhost.d
     - html:/usr/share/nginx/html
     - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
     - 80:80
     - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
     - proxy

  letsencrypt:
    container_name: reverse-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
     - certs:/etc/nginx/certs
     - vhost.d:/etc/nginx/vhost.d
     - html:/usr/share/nginx/html
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - proxy
    depends_on:
     - proxy

networks:
  proxy:
    name: reverse-proxy

volumes:
  vhost.d:
  html:
  certs:
